# -*- coding: utf-8 -*-
"""Ali_Inamdar_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SUtSZX_NbuDuvU1e0ik4P43_olqUcB7r
"""

! pip install wyn-agent

from google.colab import userdata
MISTRAL_API_KEY = userdata.get('Ali_Mistral_API_Key')

from wyn_agent.mistral_agent import ChatBot

bot = ChatBot(
    api_key=MISTRAL_API_KEY,
    agent_id="ag:ebf9813d:20250204:untitled-agent:8152e9d0",
    protocol="You are a code assistant."
)

bot.run_mistral_agent()

